version: '3.8'

volumes: 
  es_data:
    name: es_data

networks:
  http_network:
    external: true
  elk_network:
    external: false

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - es_data:/usr/share/elasticsearch/data
    container_name: elasticsearch
    restart: on-failure
#    ports:
#      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      ELASTIC_PASSWORD: changeme
      cluster.name: es-cluster
      bootstrap.memory_lock: "true"
      http.cors.enabled: "true"
      http.cors.allow-origin: "*"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - http_network
      - elk_network

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
 #     - "9600:9600"
    container_name: logstash
    restart: on-failure
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
      ELASTICSEARCH_HOSTS: http://elasticsearch_node1:9200
    networks:
      - http_network
      - elk_network
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    container_name: kibana
    restart: on-failure
    environment:
      ELASTICSEARCH_PASSWORD: changeme
    networks:
      - http_network
      - elk_network
    depends_on:
      - elasticsearch