ARG ELK_VERSION

# https://github.com/elastic/elasticsearch-docker
#FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
FROM elasticsearch:${ELK_VERSION}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
#RUN bin/elasticsearch-plugin install -b https://store.kcdn.ir/elk/prometheus-exporter-7.1.0.0.zip
